In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [62]:
df = pd.read_csv('data.csv')

In [63]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0  100.132027         1   67          1           0              1
1   99.761447         1   10          0           0              0
2   98.020578         1   75          1           1              1
3   99.237362         0   71          1          -1              1
4  100.025546         1   11          1           0              1

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2517 non-null   float64
 1   bodyPain       2517 non-null   int64  
 2   age            2517 non-null   int64  
 3   runnyNose      2517 non-null   int64  
 4   diffBreath     2517 non-null   int64  
 5   infectionProb  2517 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 118.1 KB


In [65]:
df.isna().sum()

fever            0
bodyPain         0
age              0
runnyNose        0
diffBreath       0
infectionProb    0
dtype: int64

In [66]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2517.000000  2517.000000  2517.000000  2517.000000  2517.000000   
mean     99.990178     0.495034    44.497815     0.518872    -0.019468   
std       1.167727     0.500075    23.342879     0.499743     0.815696   
min      98.001093     0.000000     5.000000     0.000000    -1.000000   
25%      98.976230     0.000000    24.000000     0.000000    -1.000000   
50%      99.982257     0.000000    44.000000     1.000000     0.000000   
75%     101.019143     1.000000    64.000000     1.000000     1.000000   
max     101.999494     1.000000    85.000000     1.000000     1.000000   

       infectionProb  
count    2517.000000  
mean        0.504966  
std         0.500075  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

In [67]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [68]:
train,test = data_split(df,0.2)

In [69]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
495    98.319281         1   21          1          -1              1
1313   99.224491         0   62          1          -1              1
2150  100.657704         1   41          0           1              1
1159  101.816005         1   61          1           1              1
289    99.187054         1   46          0           1              0
...          ...       ...  ...        ...         ...            ...
1638  101.020426         1   67          1          -1              0
1095   99.317221         1    5          1           0              1
1130  101.563128         0   38          1           0              1
1294  101.118131         0    5          1          -1              0
860    99.073791         1    8          0           0              1

[2014 rows x 6 columns]

In [70]:

X_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()
X_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [71]:
Y_train = train[['infectionProb']].to_numpy().reshape(2014,)
Y_test = test[['infectionProb']].to_numpy().reshape(503,)

In [72]:
Y_train

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [73]:
#from sklearn import preprocessing

In [74]:
#X_train=preprocessing.normalize(X_train)
#X_test=preprocessing.normalize(X_test)

In [75]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [76]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [77]:
from sklearn.linear_model import LogisticRegression

In [78]:
model = LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [79]:
prediction=model.predict(X_test)

In [80]:
prediction

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,

In [82]:

model.predict_proba([[100,1,22,1,1]])

array([[0.96741992, 0.03258008]])

In [84]:
input_features = [100,1,22,1,1]
infectionProbability = model.predict_proba([input_features])[0][0]
infectionProbability

0.9674199162894076

In [85]:
import pickle

In [87]:
pickle.dump(model, open("covidmodel.pkl","wb"))#give the classifier object name and file name